# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "DIAL Lab"

author:
  # facebook:         your-id
  # youtubeUser:      your-id
  # youtubeChannel:   your-id
  # twitter:          your-id
  github:           diallab
  # stackoverflow:    your-id
  # quora:            your-id
  # linkedin:         your-id
  # pinterest:        your-id
  # googlePlus:       your-id
  # instagram:        your-id
  # reddit:           your-id
  # medium:           your-id
  # tumblr:           your-id
  email:            kdj2614@naver.com

copyright:
  year:             2019
  name:             Daejin Kim, Jiwoo Kim

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               ""

# URL
url:                "https://diallab.github.io" # the base hostname & protocol for your site
#url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           7
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "People"
    url:            "/people"
  - name:           "Research"
    url:            "/research"
  - name:           "Publication"
    url:            "/publication"
  - name:           "News"
    url:            "/news"
  - name:           "Seminar"
    url:            "/seminar"
  - name:           "Tags"
    url:            "/tags"
  #- name:           "Events"
  #  url:            "/events"
  #- name:           "Github"
  #  url:            "https://github.com/diallab"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "authors"
    values:
      layout:       "author"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor, Form]

future: true

collections:
  authors:
    output: true
    permalink: /authors/:path/